# Generated by Django 5.1.7 on 2025-06-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_user_license_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinvitation',
            name='family',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='family',
        ),
        migrations.RemoveField(
            model_name='familyinvitation',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='familyinvitation',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyCommunity',
        ),
        migrations.DeleteModel(
            name='FamilyInvitation',
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
