# Generated by Django 5.1.7 on 2025-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_familyinvitation_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/'),
        ),
    ]
